// <auto-generated />
using System;
using MarcosDuran_AP1_P2.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarcosDuran_AP1_P2.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241124022732_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarcosDuran_AP1_P2.Models.Articulos", b =>
                {
                    b.Property<int>("ArticuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticuloId"));

                    b.Property<int>("Costo")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Existencia")
                        .HasColumnType("int");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.HasKey("ArticuloId");

                    b.ToTable("Articulos");

                    b.HasData(
                        new
                        {
                            ArticuloId = 1,
                            Costo = 700,
                            Descripcion = "Mouse",
                            Existencia = 15,
                            Precio = 800
                        },
                        new
                        {
                            ArticuloId = 2,
                            Costo = 7000,
                            Descripcion = "Monitor",
                            Existencia = 6,
                            Precio = 7500
                        },
                        new
                        {
                            ArticuloId = 3,
                            Costo = 2000,
                            Descripcion = "Teclado",
                            Existencia = 8,
                            Precio = 2050
                        },
                        new
                        {
                            ArticuloId = 4,
                            Costo = 35000,
                            Descripcion = "Tarjeta grafica",
                            Existencia = 20,
                            Precio = 38000
                        },
                        new
                        {
                            ArticuloId = 5,
                            Costo = 1500,
                            Descripcion = "Ram",
                            Existencia = 50,
                            Precio = 1800
                        },
                        new
                        {
                            ArticuloId = 6,
                            Costo = 3500,
                            Descripcion = "CPU",
                            Existencia = 15,
                            Precio = 3000
                        });
                });

            modelBuilder.Entity("MarcosDuran_AP1_P2.Models.RegistroCombo", b =>
                {
                    b.Property<int>("ComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<bool>("Vendido")
                        .HasColumnType("bit");

                    b.HasKey("ComboId");

                    b.ToTable("RegistroCombo");

                    b.HasData(
                        new
                        {
                            ComboId = 1,
                            Descripcion = "Monitor, mouse y teclado",
                            Fecha = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 0,
                            Vendido = false
                        },
                        new
                        {
                            ComboId = 2,
                            Descripcion = "Computador Preensamblado",
                            Fecha = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 0,
                            Vendido = false
                        },
                        new
                        {
                            ComboId = 3,
                            Descripcion = "Ram, CPU y tarjeta grafica",
                            Fecha = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 0,
                            Vendido = false
                        },
                        new
                        {
                            ComboId = 4,
                            Descripcion = "Mouse y teclado",
                            Fecha = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 0,
                            Vendido = false
                        });
                });

            modelBuilder.Entity("MarcosDuran_AP1_P2.Models.RegistroComboDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ComboId")
                        .HasColumnType("int");

                    b.Property<int>("Costo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("DetalleId");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("ComboId");

                    b.ToTable("RegistroComboDetalle");
                });

            modelBuilder.Entity("MarcosDuran_AP1_P2.Models.RegistroComboDetalle", b =>
                {
                    b.HasOne("MarcosDuran_AP1_P2.Models.Articulos", "Articulos")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarcosDuran_AP1_P2.Models.RegistroCombo", "registroCombo")
                        .WithMany("registroComboDetalle")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulos");

                    b.Navigation("registroCombo");
                });

            modelBuilder.Entity("MarcosDuran_AP1_P2.Models.RegistroCombo", b =>
                {
                    b.Navigation("registroComboDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
