// <auto-generated />
using System;
using MarcosDuran_AP1_P2.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarcosDuran_AP1_P2.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241118230917_NuevosModelos")]
    partial class NuevosModelos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarcosDuran_AP1_P2.Models.Articulos", b =>
                {
                    b.Property<int>("ArticuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticuloId"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Existencia")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ArticuloId");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("MarcosDuran_AP1_P2.Models.RegistroCombo", b =>
                {
                    b.Property<int>("ComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<int?>("RegistroComboDetalleDetalleId")
                        .HasColumnType("int");

                    b.Property<int>("Vendido")
                        .HasColumnType("int");

                    b.HasKey("ComboId");

                    b.HasIndex("RegistroComboDetalleDetalleId");

                    b.ToTable("RegistroCombo");
                });

            modelBuilder.Entity("MarcosDuran_AP1_P2.Models.RegistroComboDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ComboId")
                        .HasColumnType("int");

                    b.Property<int>("Costo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("DetalleId");

                    b.ToTable("RegistroComboDetalle");
                });

            modelBuilder.Entity("MarcosDuran_AP1_P2.Models.RegistroCombo", b =>
                {
                    b.HasOne("MarcosDuran_AP1_P2.Models.RegistroComboDetalle", null)
                        .WithMany("comboDetalle")
                        .HasForeignKey("RegistroComboDetalleDetalleId");
                });

            modelBuilder.Entity("MarcosDuran_AP1_P2.Models.RegistroComboDetalle", b =>
                {
                    b.Navigation("comboDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
